apiVersion: v1
kind: ConfigMap
metadata:
  name: freeswitch
  labels:
    app: freeswitch
    project: telephoneorg
    environment: production
data:
  erlang.hostname: long
  freeswitch.log.level: info
  freeswitch.log.color: 'true'
  freeswitch.rtp.port-range: '16384-32768'
  freeswitch.disable-nat-detection: 'false'
  freeswitch.tls.enable: 'false'
