#!/usr/bin/env bash

function errtrap {
  es=$?
  echo "ERROR line $1: Command exited with status $es."
}

trap 'errtrap $LINENO' ERR  # is run whenever a command in the surrounding script or function exits with non-zero status

HELM_DIR=./deploy/helm-charts
HELM_MANIFEST_FILE=./deploy/helm-charts/index.yaml
HELM_MANIFEST=$(cat "${HELM_MANIFEST_FILE}")

function get_manifest_charts() {
    echo "${HELM_MANIFEST}" | yq -c -r '.charts | .[]'
}

function get_rest() {
    local rest=$(echo "${1}" | jq -c -r 'to_entries | map(select(.key != "package"))')
    local rest_str=$(echo "${rest}" | jq -r 'map("--" + .key + " " + .value) | join(" ")')
    echo "${rest_str}"
}

function install_chart() {
    local package=$1
    local package_name=$(cat <<< $package | jq -r '.package')

    echo "Installing chart ${package_name}..."

    local rest=`get_rest "$package"`

    helm install "${opts}" "${package_name}"
}

function install_manifest_charts() {
    echo "Installing manifest charts..."

    local charts="$(get_manifest_charts)"
    for chart in $(echo "${charts}"); do
        install_chart "${chart}"
    done
}

install_manifest_charts
