apiVersion: kubedb.com/v1alpha1
kind: Memcached
metadata:
  name: kubedb-memcached
  namespace: default
spec:
  replicas: 3
  version: 1.5.4
  doNotPause: true
  resources:
    requests:
      memory: 64Mi
      cpu: 250m
    limits:
      memory: 128Mi
      cpu: 500m
